### PR TITLE
:zap: improves caching

### PR DESCRIPTION
**Pull request by sethu1012**
- Improves performance by caching all static resources

### CODE REVIEW

**Review by RobertBrunhage — CHANGES_REQUESTED** [review]
Looks good, just a minor tweak that I could see!

**Comment by sethu1012** [comment]
Want me add features/fix bugs to this branch?

**Comment by RobertBrunhage** [comment]
> Want me add features/fix bugs to this branch?

Not sure what you mean, I would recommend just doing the change discussed and we can merge, than if it's anything else we can take that in a separate PR! 😀

**Comment by RobertBrunhage** [comment]
Closing this as it's stale

**Pull request closed without merging**
